### ISSUE TITLE
Test v0.2 compatibility

### ISSUE THREAD

**Issue by huang195** [iter8-tools/iter8-trend#43]
For iter8 v0.2 (once all the important changes are merged), need to test iter8-trend's compatibility with it.

**Comment by huang195** [comment]
@kalantar since I verified that iter8-trend works for v0.2, I'm assigning this issue to you to make sure things are also working for anyone other than myself.

**Comment by kalantar** [comment]
I found the following exception when there is an experiment that specifies baseline/candidate as services. This experiment can be completed. Or it will happen when the experiment finishes. Deletion of the offending experiment and restarting iter8-trend seems to get things working again.

```
Exception happened during processing of request from ('172.30.166.163', 38428)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/exposition.py", line 152, in do_GET
    output = encoder(registry)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/openmetrics/exposition.py", line 14, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 75, in collect
    for metric in collector.collect():
  File "./iter8-trend.py", line 276, in collect
    self.experiments[exp].serviceName,
AttributeError: 'Experiment' object has no attribute 'serviceName'
```

**Comment by huang195** [comment]
The issue is caused by a change in the Experiment CRD for v0.2. Prior to v0.2, targetService looks like
```  
  targetService:
    apiVersion: v1
    baseline: reviews-v2
    candidate: reviews-v3
    kind: Deployment
    name: reviews
```

Afterwards, it looks like
```
targetService:
    baseline: productpage-v1
    candidate: productpage-v2
    hosts:
    - gateway: productpage-service
      name: productpage.example.com
    kind: Service
```

Iter8-trend uses `targetService.name` to group a series of successful experiments to view trend over time. Now that this field is no longer there, it breaks.

**Comment by huang195** [comment]
@kalantar I think I fixed the issue due to the above problem. I was able to test it in my environment. If you don't mind, can you deploy it in your environment and see if the problematic new scenario 5 is now working? Thanks!

**Comment by kalantar** [comment]
@huang195 the problems seem to be gone.

**Comment by kalantar** [comment]
@huang195 can we close this?

**Comment by huang195** [comment]
Closing. Forgot about this.
